import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/helpers/ClientLayout";
import { Providers } from "@/helpers/Providers";
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "next-themes";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "CloudYukti",
  description: "Generated by Team 3A's",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth" suppressHydrationWarning={true}>
      <body
        className={`${inter.className} antialiased `}
      >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <Providers>
                <ClientLayout>
                  {children}
                  <Toaster />
                </ClientLayout>
            </Providers>
          </ThemeProvider>
      </body>
    </html>
  );
}
